export const buttons = [
  {
    label: 'C',
    value: 'C',
    style: { backgroundColor: 'var(--token-button-secondary-gray' },
  },
  {
    label: '/',
    value: '/',
    style: { backgroundColor: 'var(--token-button-secondary-gray' },
  },
  {
    label: '*',
    value: '*',
    style: { backgroundColor: 'var(--token-button-secondary-gray' },
  },
  { label: '-', value: '-', style: { backgroundColor: 'var(--token-button-primary' } },
  { label: '7', value: '7', style: { backgroundColor: 'var(--token-button-white' } },
  { label: '8', value: '8', style: { backgroundColor: 'var(--token-button-white' } },
  { label: '9', value: '9', style: { backgroundColor: 'var(--token-button-white' } },
  { label: '+', value: '+', style: { backgroundColor: 'var(--token-button-primary' } },
  { label: '4', value: '4', style: { backgroundColor: 'var(--token-button-white' } },
  { label: '5', value: '5', style: { backgroundColor: 'var(--token-button-white' } },
  { label: '6', value: '6', style: { backgroundColor: 'var(--token-button-white' } },
  { label: '=', value: '=', style: { backgroundColor: 'var(--token-button-primary' } },
  { label: '1', value: '1', style: { backgroundColor: 'var(--token-button-white' } },
  { label: '2', value: '2', style: { backgroundColor: 'var(--token-button-white' } },
  { label: '3', value: '3', style: { backgroundColor: 'var(--token-button-white' } },
  { label: '.', value: '.', style: { backgroundColor: 'var(--token-button-white' } },
  {
    label: '0',
    value: '0',
    style: { backgroundColor: 'var(--token-button-white)' },
  },
]
